# Generated by Django 3.0.5 on 2022-08-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('DOJ', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
