# Generated by Django 3.0.5 on 2022-08-25 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_auto_20220825_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 10, 34, 30, 868700), null=True),
        ),
    ]
