# Generated by Django 3.0.5 on 2022-08-25 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0003_auto_20220825_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 12, 19, 1, 412154), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
